using System.Numerics;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Medical.Sleeper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Medical.Sleeper.UI;

[GenerateTypedNameReferences]
public sealed partial class SleeperWindow : FancyWindow
{
    public event Action? OnEjectPatientPressed;
    public event Action? OnEjectBeakerPressed;
    public event Action<bool>? OnToggleFilter;
    public event Action<bool>? OnTogglePump;
    public event Action<int>? OnSetStasis;
    public event Action<string, FixedPoint2>? OnInjectChemical;

    private bool _populating;

    public SleeperWindow()
    {
        RobustXamlLoader.Load(this);

        EjectPatientButton.OnPressed += _ => OnEjectPatientPressed?.Invoke();
        EjectBeakerButton.OnPressed += _ => OnEjectBeakerPressed?.Invoke();
        DialysisToggle.OnToggled += args => OnToggleFilter?.Invoke(args.Pressed);
        PumpToggle.OnToggled += args => OnTogglePump?.Invoke(args.Pressed);
        StasisSelector.OnItemSelected += args =>
        {
            if (!_populating)
                OnSetStasis?.Invoke((int)args.Id);
        };
        InjectButton.OnPressed += _ =>
        {
            var amount = FixedPoint2.New(InjectAmount.Value);
            OnInjectChemical?.Invoke("", amount);
        };
    }

    public void Populate(SleeperUserMessage msg)
    {
        _populating = true;

        if (msg.HasOccupant)
        {
            var status = new StringBuilder();
            status.AppendLine(Loc.GetString("health-analyzer-brain-activity", ("activity", msg.Health.BrainActivity)));
            status.AppendLine(Loc.GetString("health-analyzer-pulse-rate", ("rate", msg.Health.PulseRate)));
            status.AppendLine(Loc.GetString("health-analyzer-oxygenation", ("oxygenation", msg.Health.BloodOxygenation)));

            if (msg.Health.Limbs != null)
            {
                foreach (var limb in msg.Health.Limbs)
                {
                    status.AppendLine(Loc.GetString("health-analyzer-limb-status",
                        ("limb", limb.Name),
                        ("brute", limb.BruteDamage),
                        ("burn", limb.BurnDamage)));
                }
            }

            PatientStatus.SetMessage(status.ToString());
        }
        else
        {
            PatientStatus.SetMessage(Loc.GetString("sleeper-no-patient"));
        }

        DialysisToggle.Pressed = msg.Filtering;
        PumpToggle.Pressed = msg.Pump;

        StasisSelector.Clear();
        foreach (var setting in msg.StasisSettings)
        {
            StasisSelector.AddItem($"{setting}x", setting);
        }
        StasisSelector.Select(msg.StasisSettings.IndexOf(msg.StasisSetting));

        ChemicalList.RemoveAllChildren();
        foreach (var chem in msg.AvailableChemicals)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
            var label = new Label { Text = chem, MinSize = new Vector2(120, 0), VerticalAlignment = VAlignment.Center };
            var btn = new Button { Text = Loc.GetString("sleeper-inject"), MinSize = new Vector2(60, 0), MaxWidth = 80 };
            var captured = chem;
            btn.OnPressed += _ =>
            {
                var amount = FixedPoint2.New(InjectAmount.Value);
                OnInjectChemical?.Invoke(captured, amount);
            };
            row.AddChild(label);
            row.AddChild(btn);
            ChemicalList.AddChild(row);
        }

        if (msg.BeakerCapacity != null && msg.Beaker != null)
        {
            var totalVol = FixedPoint2.Zero;
            foreach (var reagent in msg.Beaker)
                totalVol += reagent.Quantity;
            BeakerStatus.Text = Loc.GetString("sleeper-beaker-status", ("volume", totalVol), ("capacity", msg.BeakerCapacity));
        }
        else
        {
            BeakerStatus.Text = Loc.GetString("sleeper-no-beaker");
        }

        LockedWarning.Visible = msg.Locked;
        _populating = false;
    }
}
