using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.Scanners;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Medical.Scanners.UI;

[GenerateTypedNameReferences]
public sealed partial class BodyScannerWindow : FancyWindow
{
    public event Action? OnScanPressed;
    public event Action? OnEjectPressed;

    public BodyScannerWindow()
    {
        RobustXamlLoader.Load(this);

        ScanButton.OnPressed += _ => OnScanPressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
    }

    public void Populate(BodyScannerUserMessage msg)
    {
        ScanResults.RemoveAllChildren();

        if (!msg.HasOccupant)
        {
            ScanResults.AddChild(new Label { Text = Loc.GetString("body-scanner-no-patient") });
            return;
        }

        var headerLabel = new Label
        {
            Text = Loc.GetString("body-scanner-scan-results-header"),
            StyleClasses = { "LabelHeadingText" }
        };
        ScanResults.AddChild(headerLabel);

        if (msg.ScanData != null)
        {
            foreach (var line in msg.ScanData)
                ScanResults.AddChild(new Label { Text = line, Margin = new Thickness(4, 2) });
        }
    }
}
