using Content.Shared._Medical.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Medical.Targeting;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    public event Action<TargetBodyPart>? OnPartSelected;

    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);

        _bodyPartControls = new()
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var (part, btn) in _bodyPartControls)
        {
            var captured = part;
            btn.MouseFilter = MouseFilterMode.Stop;
            btn.OnPressed += _ =>
            {
                OnPartSelected?.Invoke(captured);
                SetBodyPartsVisible(captured);
            };
        }

        TargetDoll.Texture = Theme.ResolveTexture("target_doll");
    }

    public void SetBodyPartsVisible(TargetBodyPart bodyPart)
    {
        foreach (var (part, btn) in _bodyPartControls)
        {
            var tex = btn.ChildCount > 0 ? btn.GetChild(0) as TextureRect : null;
            var hover = btn.ChildCount > 1 ? btn.GetChild(1) as TextureRect : null;

            if (tex != null)
                tex.Visible = part != bodyPart;
            if (hover != null)
                hover.Visible = part == bodyPart;
        }
    }

    public void SetTargetDollVisible(bool visible) => Visible = visible;

    public IReadOnlyDictionary<TargetBodyPart, TextureButton> GetBodyPartButtons() => _bodyPartControls;
}
